
import static java.lang.Thread.sleep;



public class NewJFrame extends javax.swing.JFrame {
  
    static int hours=0;
    static int minutes=0;
    static int seconds=0;
    static int miliseconds=0;
    static boolean state=true;
    public NewJFrame() {
        initComponents();
        turnoff();
    }
   private void turnoff(){
      
      bstop.setEnabled(false);
      bpause.setEnabled(false);
      blap1.setEnabled(false);
      blap2.setEnabled(false);
      blap3.setEnabled(false);
      blap4.setEnabled(false);
      blap5.setEnabled(false);
           
       }
   void clean(){
       bcontinue.setVisible(false);
       blap2.setVisible(false);
       blap3.setVisible(false);
       blap4.setVisible(false);
       blap5.setVisible(false);
       jlap1.setVisible(false);
       jlap2.setVisible(false);
       jlap3.setVisible(false);
       jlap4.setVisible(false);
       jlap5.setVisible(false);
       jLabel9.setText("00:00:00:000");
       jlap1.setText("00:00:00:000");
       jlap2.setText("00:00:00:000");
       jlap3.setText("00:00:00:000");
       jlap4.setText("00:00:00:000");
       jlap5.setText("00:00:00:000");
       
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlap5 = new javax.swing.JLabel();
        bstop = new javax.swing.JButton();
        bstart = new javax.swing.JButton();
        bpause = new javax.swing.JButton();
        bcontinue = new javax.swing.JButton();
        blap2 = new javax.swing.JButton();
        blap3 = new javax.swing.JButton();
        blap1 = new javax.swing.JButton();
        blap4 = new javax.swing.JButton();
        blap5 = new javax.swing.JButton();
        jlap4 = new javax.swing.JLabel();
        jlap3 = new javax.swing.JLabel();
        jlap2 = new javax.swing.JLabel();
        jlap1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("00:00:00:000");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("StopWatch App");

        jlap5.setBackground(new java.awt.Color(255, 204, 204));
        jlap5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap5.setText("00:00:00:000");

        bstop.setBackground(new java.awt.Color(0, 255, 204));
        bstop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bstop.setText("STOP");
        bstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstopActionPerformed(evt);
            }
        });

        bstart.setBackground(new java.awt.Color(204, 255, 204));
        bstart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bstart.setText("START");
        bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstartActionPerformed(evt);
            }
        });

        bpause.setBackground(new java.awt.Color(255, 204, 51));
        bpause.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bpause.setText("PAUSE");
        bpause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpauseActionPerformed(evt);
            }
        });

        bcontinue.setBackground(new java.awt.Color(51, 255, 255));
        bcontinue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bcontinue.setText("CONTINUE");
        bcontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcontinueActionPerformed(evt);
            }
        });

        blap2.setBackground(new java.awt.Color(102, 255, 102));
        blap2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blap2.setText("LAP 2");
        blap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap2ActionPerformed(evt);
            }
        });

        blap3.setBackground(new java.awt.Color(51, 255, 51));
        blap3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blap3.setText("LAP 3");
        blap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap3ActionPerformed(evt);
            }
        });

        blap1.setBackground(new java.awt.Color(0, 255, 0));
        blap1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blap1.setText("LAP 1");
        blap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap1ActionPerformed(evt);
            }
        });

        blap4.setBackground(new java.awt.Color(51, 255, 51));
        blap4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blap4.setText("LAP 4");
        blap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap4ActionPerformed(evt);
            }
        });

        blap5.setBackground(new java.awt.Color(51, 255, 51));
        blap5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blap5.setText("LAP 5");
        blap5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap5ActionPerformed(evt);
            }
        });

        jlap4.setBackground(new java.awt.Color(255, 204, 204));
        jlap4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap4.setText("00:00:00:000");

        jlap3.setBackground(new java.awt.Color(255, 204, 204));
        jlap3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap3.setText("00:00:00:000");

        jlap2.setBackground(new java.awt.Color(255, 204, 204));
        jlap2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap2.setText("00:00:00:000");

        jlap1.setBackground(new java.awt.Color(255, 204, 204));
        jlap1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap1.setText("00:00:00:000");

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("00:00:00:000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bcontinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bstop)
                                .addGap(39, 39, 39)
                                .addComponent(bpause)
                                .addGap(33, 33, 33)
                                .addComponent(bstart)))))
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blap2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blap1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blap3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blap4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blap5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlap1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlap2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlap3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlap4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlap5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bstop)
                            .addComponent(bstart)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bpause)))
                .addGap(18, 18, 18)
                .addComponent(bcontinue)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blap1)
                    .addComponent(jlap1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blap2)
                    .addComponent(jlap2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blap3)
                    .addComponent(jlap3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blap4)
                    .addComponent(jlap4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blap5)
                    .addComponent(jlap5))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstartActionPerformed
        // TODO add your handling code here:
        bpause.setEnabled(true);
        blap1.setEnabled(true);
        bstart.setEnabled(false);
        bstop.setEnabled(false);
        bcontinue.setVisible(false);
        state=true;
        Thread time;
        time = new Thread() {
            @Override
            public void run(){
                for(;;){
                    if(state==true){
                        try{
                            sleep(1);
                            if(miliseconds>=1000){
                                miliseconds=0;
                                seconds ++;
                            }
                            if(seconds>=60){
                                seconds=0;
                                minutes ++;
                            }
                            if(minutes>=60){
                                minutes=0;
                                hours ++;
                            }
                            
                            miliseconds ++;
                            
                            jLabel9.setText(hours+":"+minutes+":"+seconds+":"+miliseconds);
                     
                        }catch (InterruptedException e){
                            
                        }
                    }
                    else{
                        break;
                    }
                }
            }
        };
        time.start();
        
    }//GEN-LAST:event_bstartActionPerformed

    private void blap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap2ActionPerformed
        // TODO add your handling code here:
         bstart.setEnabled(false);
        jlap2.setVisible(true);
        blap3.setVisible(true);
        blap3.setEnabled(true);
        bcontinue.setVisible(false);
        jlap2.setText(jLabel9.getText());
    }//GEN-LAST:event_blap2ActionPerformed

    private void blap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap3ActionPerformed
        // TODO add your handling code here:
         bstart.setEnabled(false);
        jlap3.setVisible(true);
        blap4.setVisible(true);
        blap4.setEnabled(true);
        bcontinue.setVisible(false);
        jlap3.setText(jLabel9.getText());
    }//GEN-LAST:event_blap3ActionPerformed

    private void blap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap1ActionPerformed
        // TODO add your handling code here:
        bstart.setEnabled(false);
        jlap1.setVisible(true);
        blap2.setVisible(true);
        blap2.setEnabled(true);
        bcontinue.setVisible(false);
        jlap1.setText(jLabel9.getText());
    }//GEN-LAST:event_blap1ActionPerformed

    private void blap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap4ActionPerformed
        // TODO add your handling code here:
         bstart.setEnabled(false);
        jlap4.setVisible(true);
        blap5.setVisible(true);
        blap5.setEnabled(true);
        bcontinue.setVisible(false);
        jlap4.setText(jLabel9.getText());
    }//GEN-LAST:event_blap4ActionPerformed

    private void blap5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap5ActionPerformed
        // TODO add your handling code here:
         bstart.setEnabled(false);
        jlap5.setVisible(true);
        blap5.setVisible(true);
        bcontinue.setVisible(false);
        jlap5.setText(jLabel9.getText());
    }//GEN-LAST:event_blap5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        blap1.setVisible(true);
        blap2.setVisible(false);
        blap3.setVisible(false);
        blap4.setVisible(false);
        blap5.setVisible(false);
        jlap1.setVisible(false);
        jlap2.setVisible(false);
        jlap3.setVisible(false);
        jlap4.setVisible(false);
        jlap5.setVisible(false);
        bcontinue.setVisible(false);
        blap2.setEnabled(true);
        blap3.setEnabled(true);
        blap4.setEnabled(true);
        blap5.setEnabled(true);
                
        
        
    }//GEN-LAST:event_formWindowActivated

    private void bpauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpauseActionPerformed
        // TODO add your handling code here:
        turnoff();
        bcontinue.setVisible(true);
        bstop.setEnabled(true);
        state=false;
    }//GEN-LAST:event_bpauseActionPerformed

    private void bstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstopActionPerformed
        // TODO add your handling code here:
        bstart.setEnabled(true);
        bpause.setEnabled(false);
        bstop.setEnabled(false);
        clean();
        state=false;
        hours=0;
        minutes=0;
        seconds=0;
        miliseconds=0;
    }//GEN-LAST:event_bstopActionPerformed

    private void bcontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcontinueActionPerformed
        // TODO add your handling code here:
        bcontinue.setVisible(false);
        bstart.setEnabled(false);
        bstop.setEnabled(false);
        bpause.setEnabled(true);
        blap1.setEnabled(true);
        blap2.setEnabled(true);
        blap3.setEnabled(true);
        blap4.setEnabled(true);
        blap5.setEnabled(true);
        state=true;
        Thread time;
        time = new Thread() {
            @Override
            public void run(){
                for(;;){
                    if(state==true){
                        try{
                            sleep(1);
                            if(miliseconds>=1000){
                                miliseconds=0;
                                seconds ++;
                            }
                            if(seconds>=60){
                                seconds=0;
                                minutes ++;
                            }
                            if(minutes>=60){
                                minutes=0;
                                hours ++;
                            }
                            
                            miliseconds ++;
                            
                            jLabel9.setText(hours+":"+minutes+":"+seconds+":"+miliseconds);
                     
                        }catch (InterruptedException e){
                            
                        }
                    }
                    else{
                        break;
                    }
                }
            }
        };
        time.start();
    }//GEN-LAST:event_bcontinueActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcontinue;
    private javax.swing.JButton blap1;
    private javax.swing.JButton blap2;
    private javax.swing.JButton blap3;
    private javax.swing.JButton blap4;
    private javax.swing.JButton blap5;
    private javax.swing.JButton bpause;
    private javax.swing.JButton bstart;
    private javax.swing.JButton bstop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlap1;
    private javax.swing.JLabel jlap2;
    private javax.swing.JLabel jlap3;
    private javax.swing.JLabel jlap4;
    private javax.swing.JLabel jlap5;
    // End of variables declaration//GEN-END:variables
}
